apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.json: |-
    {
      "TENANT_ID": "{{ .Values.config.TENANT_ID }}",
      "TENANT_NAME": "{{ .Values.config.TENANT_NAME }}",
      "TENANT_TOPIC": "{{ .Values.config.TENANT_TOPIC }}",
      "SYSTEM_PROMPT": "{{ .Values.config.SYSTEM_PROMPT }}",
      "TAVILY_API_KEY": "{{ .Values.config.TAVILY_API_KEY }}",
      "OLLAMA_URL": "{{ .Values.config.OLLAMA_URL }}",
      "OLLAMA_MODEL": "{{ .Values.config.OLLAMA_MODEL }}",
      "MAX_TAVILY_RESULTS": {{ .Values.config.MAX_TAVILY_RESULTS }},
      "TEST_MODE": "{{ .Values.config.TEST_MODE }}"
    }
